# Generated by Django 5.0.6 on 2024-05-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0006_marketing_gastos_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_producto', models.TextField(blank=True, max_length=250, null=True)),
                ('categoria_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('ciclo_vida', models.CharField(blank=True, max_length=50, null=True)),
                ('costo_desarrollo', models.FloatField(blank=True, null=True)),
                ('costo_produccion', models.FloatField(blank=True, null=True)),
                ('precio_venta', models.FloatField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendimiento.proyecto')),
            ],
        ),
    ]
