# Generated by Django 5.0.6 on 2024-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0007_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ciclo_vida',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
