# Generated by Django 5.0.6 on 2024-05-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0008_alter_producto_ciclo_vida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.TextField(blank=True, max_length=250, null=True)),
                ('vision', models.TextField(blank=True, max_length=250, null=True)),
                ('valores', models.TextField(blank=True, max_length=250, null=True)),
                ('objetivos', models.TextField(blank=True, max_length=250, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendimiento.proyecto')),
            ],
        ),
    ]
