# Generated by Django 5.0.6 on 2024-05-19 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0009_identidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_cargo', models.TextField(blank=True, max_length=500, null=True)),
                ('requisitos_cargo', models.TextField(blank=True, max_length=500, null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('numero_empleados', models.IntegerField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendimiento.proyecto')),
            ],
        ),
    ]
