# Generated by Django 5.0.6 on 2024-05-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0010_cargoempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ciclo_vida',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
