# Generated by Django 3.2.25 on 2024-06-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0013_alter_marketing_mercado_objetivo_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='segmentacion_cliente',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
